name: Lint

on:
  pull_request:
    paths:
      - '**/*.go'
      - 'Dockerfile'
  push:
    paths:
      - '**/*.go'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run semgrep
        run: |
          curl -s https://semgrep.dev/secrets/install | bash
          semgrep --config=p/r2c --autofix

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run hadolint
        uses: hadolint/hadolint-action@v2
        with:
          dockerfile: Dockerfile

  superlinter:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          RUN_LOCAL: true
